### ISSUE TITLE
Colab - ModuleNotFoundError: No module named 'wheel.pep425tags'

### ISSUE THREAD

**Issue by bharathvarma008** [ContinualAI/colab#9]
Hey, 

I was checking out some introduction notebooks on colab.reasearch <notebooks/Generative_Replay.ipynb> and found that "wheel.pep425tags" is not available. 

So I have tried to restart instance and then install again a version that supports corresponding functions to use the notebook. It worked. 

The supported version is "wheel==0.34.2" as per [this link](https://nomodulenamed.com/m/wheel.pep425tags).

But that gave further incompatibility issues while installing the next few libraries in the code. I guess this is more of a dependency issue and hence Error logs shared below for reference. Kindly help here. Thanks, ~ Bharath. 

-----------------------------------------
Platform: cp36-cp36m Accelerator: cu80
     |████████████████████████████████| 484.0MB 1.1MB/s 
     |████████████████████████████████| 12.8MB 220kB/s 
     |████████████████████████████████| 2.2MB 43.1MB/s 
     |████████████████████████████████| 14.5MB 258kB/s 
ERROR: torchvision 0.8.2 has requirement torch==1.7.1, but you'll have torch 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.0 has requirement wheel~=0.35, but you'll have wheel 0.34.2 which is incompatible.
ERROR: fastai 1.0.61 has requirement torch>=1.0.0, but you'll have torch 0.4.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
Torch 0.4.0 CUDA 8.0.61

**Comment by AndreaCossu** [comment]
Thank you for the warning :grin: Currently, we are in the process of entirely restructuring our notebooks. Hopefully, there will be a working version soon.
Anyway, for a quick solution you can run the notebook in colab where PyTorch is already installed or on your local PC if you already have Pytorch. When doing that, simply replace the first code cell with
```
import torch
```

Since wheel is required only to install the appropriate version of PyTorch, this should work. Let me know if you have any other issues!
